version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocritic
    - goheader
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gomodguard
    - nlreturn
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - wrapcheck
    - wsl
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    goheader:
      template: |-
        Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
        or more contributor license agreements. Licensed under the Elastic License 2.0;
        you may not use this file except in compliance with the Elastic License 2.0.
    nolintlint:
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
          - scopelint
          - unparam
        path: (^test/.*\.go|.*_test\.go)
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 25
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
