---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eck-diagnostics
  description: Buildkite Pipeline for eck-diagnostics
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/eck-diagnostics

spec:
  type: buildkite-pipeline
  owner: group:cloud-k8s-operator
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eck-diagnostics
    spec:
      repository: elastic/eck-diagnostics
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        cloud-k8s-operator:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
