
env:
  DOCKER_REGISTRY_VAULT_PATH: secret/ci/elastic-eck-diagnostics/docker-registry-elastic

steps:

  - label: ":go: lint"
    command: make lint
    agents:
      image: "golang:1.23.0"
      cpu: "4"
      memory: "8G"

  - label: ":go: tests"
    command: make unit-tests
    agents:
      image: "golang:1.23.0"
      cpu: "4"
      memory: "4G"

  - wait

  - label: ":docker: build"
    commands:
      - .buildkite/registry-login.sh
      - drivah build --push .
    agents:
      image: "docker.elastic.co/ci-agent-images/drivah:0.25.3"
      cpu: "4"
      memory: "4G"
      ephemeralStorage: "20G"
