apiVersion: v1
kind: Pod
metadata:
  name: {{ .PodName }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: eck-diagnostics
spec:
  terminationGracePeriodSeconds: 0
  automountServiceAccountToken: false
  containers:
    - name: {{ .MainContainerName }}
      image: {{ .DiagnosticImage }}
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
      {{ if and (and .ESSecretName .ESSecretKey) (not (and .ESUsername .ESPassword)) }}
      env:
        - name: ES_PW
          valueFrom:
            secretKeyRef:
              name: {{ .ESSecretName }}
              key: {{ .ESSecretKey }}
      {{ end }}
      {{ if and .ESUsername .ESPassword }}
      env:
        - name: ES_USERNAME
          value: {{ .ESUsername }}
        - name: ES_PASSWORD
          value: {{ .ESPassword }}
      {{ end }}
      volumeMounts:
        - name: output
          mountPath: {{ .OutputDir }}
      command: [sh, -c]
      args:
        - |
          cd {{ .OutputDir }}
          /support-diagnostics/diagnostics.sh -h {{.SVCName}} --type {{.Type}} --bypassDiagVerify \
            {{if and (and .ESSecretName .ESSecretKey) (not (and .ESUsername .ESPassword))}} -u {{ .ESSecretKey }} --passwordText $ES_PW{{end}} \
            {{if and .ESUsername .ESPassword}} -u $ES_USERNAME --passwordText $ES_PASSWORD{{end}} \
            {{if .TLS}} -s --noVerify {{end}} \
            -o .
          touch ready
          while true; do sleep 1; done;
      readinessProbe:
        exec:
          command:
            - cat
            - {{ .OutputDir }}/ready
      resources:
        requests:
          memory: 20Mi
          cpu: 100m
        limits:
          memory: 2Gi
          cpu: 1
  volumes:
    - name: output
      emptyDir: {}
  restartPolicy: Never
