apiVersion: v1
kind: Pod
metadata:
  name: {{ .PodName }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: eck-diagnostics
spec:
  terminationGracePeriodSeconds: 0
  automountServiceAccountToken: false
  containers:
    - name: {{ .MainContainerName }}
      image: {{ .DiagnosticImage }}
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
      env:
        - name: ES_PW
          valueFrom:
            secretKeyRef:
              name: {{ .ESName }}-es-elastic-user
              key: elastic
      volumeMounts:
        - name: output
          mountPath: {{ .OutputDir }}
      command: [sh, -c]
      args:
        - |
          cd {{ .OutputDir }}
          /support-diagnostics/diagnostics.sh -h {{.SVCName}} --type {{.Type}} --bypassDiagVerify -u elastic --passwordText $ES_PW {{if .TLS}}-s --noVerify{{end}} -o .
          touch ready
          while true; do sleep 1; done;
      readinessProbe:
        exec:
          command:
            - cat
            - {{ .OutputDir }}/ready
      resources:
        requests:
          memory: 20Mi
          cpu: 100m
        limits:
          memory: 2Gi
          cpu: 1
  volumes:
    - name: output
      emptyDir: {}
  restartPolicy: Never
